/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/projects/{projectId}/keys/{keyPath}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Push Translation
         * @description Store a machine translation pushed by `deepl sync push`.
         *
         *     DeepL Sync re-sends every translated key on each push. The incoming value is compared
         *     with the last value DeepL delivered (`pushed_value`), not with the current value:
         *     - same as the current value (e.g. a reviewer's edit coming back after pull) or as the
         *       last delivery (the old machine translation re-sent before pull): nothing new; the
         *       current value and its status are kept;
         *     - anything else: DeepL produced a new translation (the source changed), so the value is
         *       replaced and goes back to `machine_translated` for review.
         */
        put: operations["push_translation_api_projects__projectId__keys__keyPath__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/keys/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Translations
         * @description Return approved translations for one locale as a flat `{key: value}` object, for `deepl sync pull`.
         */
        get: operations["export_translations_api_projects__projectId__keys_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Project Status
         * @description Key count and per-locale review progress. Reserved in the contract; used by Stringherd's UI.
         */
        get: operations["project_status_api_projects__projectId__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Upload Source
         * @description Upload a full snapshot of source strings for one catalog file.
         *
         *     Send every source string each time: Stringherd compares with what it has and reports
         *     what was created, filled, updated, unchanged or removed. When a source string changes,
         *     approved translations of that key go back to review.
         */
        put: operations["upload_source_api_projects__projectId__source_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Check email and password; on success set an HttpOnly session cookie.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description End this browser's session. Safe to call when already signed out.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description The signed-in user and their assignments.
         */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_admin_users_get"];
        put?: never;
        /**
         * Create User
         * @description Create a user with a temporary password the admin shares with them.
         */
        post: operations["create_user_api_admin_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update User
         * @description Change name, role, active state or password. A password change or deactivation signs the user out.
         */
        patch: operations["update_user_api_admin_users__user_id__patch"];
        trace?: never;
    };
    "/api/admin/users/{user_id}/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Assignment
         * @description Let a user review one language of one project.
         */
        post: operations["add_assignment_api_admin_users__user_id__assignments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}/assignments/{project_id}/{locale}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Assignment */
        delete: operations["remove_assignment_api_admin_users__user_id__assignments__project_id___locale__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Projects
         * @description Projects and languages the signed-in user can review, with progress counts.
         */
        get: operations["list_projects_api_review_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/projects/{projectId}/locales/{locale}/strings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Strings
         * @description Source and translation side by side for one language, filterable and paginated.
         */
        get: operations["list_strings_api_review_projects__projectId__locales__locale__strings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/projects/{projectId}/locales/{locale}/strings/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Approve
         * @description Approve several translations at once, as they are.
         */
        post: operations["bulk_approve_api_review_projects__projectId__locales__locale__strings_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/projects/{projectId}/locales/{locale}/strings/{keyPath}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit String
         * @description Edit a translation, approve it, or both in one call.
         *
         *     - value only: saves the edit and leaves it unapproved (like an unconfirmed segment)
         *     - approved=true: approves the current (or newly edited) value and records who approved it
         *     - approved=false: withdraws an approval
         */
        patch: operations["edit_string_api_review_projects__projectId__locales__locale__strings__keyPath__patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness check that also confirms the database is reachable.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssignmentIn */
        AssignmentIn: {
            /**
             * Project Id
             * @example fitjournal
             */
            project_id: string;
            /**
             * Locale
             * @example fr
             */
            locale: string;
        };
        /** AssignmentOut */
        AssignmentOut: {
            /** Project Id */
            project_id: string;
            /** Locale */
            locale: string;
        };
        /** BulkApprove */
        BulkApprove: {
            /** Keys */
            keys: string[];
        };
        /** BulkApproveResult */
        BulkApproveResult: {
            /** Approved */
            approved: number;
            /** Already Approved */
            already_approved: number;
            /** Not Found */
            not_found: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LocaleCounts */
        LocaleCounts: {
            /**
             * Machine Translated
             * @default 0
             */
            machine_translated: number;
            /**
             * Approved
             * @default 0
             */
            approved: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** ProjectStatus */
        ProjectStatus: {
            /** Project Id */
            project_id: string;
            /** Keys */
            keys: number;
            /** Locales */
            locales: {
                [key: string]: components["schemas"]["LocaleCounts"];
            };
        };
        /** PushResult */
        PushResult: {
            /** Key */
            key: string;
            /** Locale */
            locale: string;
            /** Status */
            status: string;
            /** Changed */
            changed: boolean;
        };
        /**
         * PushTranslation
         * @description Body of `PUT /api/projects/{projectId}/keys/{keyPath}`, as sent by `deepl sync push`.
         */
        PushTranslation: {
            /**
             * Locale
             * @example de
             */
            locale: string;
            /**
             * Value
             * @example Speichern
             */
            value: string;
        };
        /**
         * ReviewEdit
         * @description Edit and/or approve one translation. Editing without approving leaves it unapproved.
         */
        ReviewEdit: {
            /** Value */
            value?: string | null;
            /** Approved */
            approved?: boolean | null;
        };
        /** ReviewLocale */
        ReviewLocale: {
            /** Locale */
            locale: string;
            /** Total */
            total: number;
            /** Machine Translated */
            machine_translated: number;
            /** Approved */
            approved: number;
        };
        /** ReviewProject */
        ReviewProject: {
            /** Project Id */
            project_id: string;
            /** Source Locale */
            source_locale: string | null;
            /** Locales */
            locales: components["schemas"]["ReviewLocale"][];
        };
        /** ReviewString */
        ReviewString: {
            /** Key */
            key: string;
            /** Source Text */
            source_text: string | null;
            /** Source File */
            source_file: string | null;
            /** Value */
            value: string;
            /** Machine Translation */
            machine_translation: string | null;
            /** Status */
            status: string;
            /** Updated At */
            updated_at: string | null;
            /** Approved At */
            approved_at: string | null;
            /** Approved By */
            approved_by: string | null;
        };
        /** ReviewStringPage */
        ReviewStringPage: {
            /** Project Id */
            project_id: string;
            /** Locale */
            locale: string;
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["ReviewString"][];
        };
        /**
         * SourceUpload
         * @description Body of `PUT /api/projects/{projectId}/source`: a full snapshot of one catalog file.
         */
        SourceUpload: {
            /**
             * Locale
             * @example en
             */
            locale: string;
            /**
             * File
             * @description Repo-relative path of the catalog, e.g. web-react/src/i18n/locales/en/common.json
             */
            file?: string | null;
            /**
             * Commit
             * @description Commit the strings were read from
             */
            commit?: string | null;
            /**
             * Strings
             * @description Flat map of key path to source text
             * @example {
             *       "login.title": "Sign in and log your next workout"
             *     }
             */
            strings: {
                [key: string]: string;
            };
        };
        /** SourceUploadResult */
        SourceUploadResult: {
            /** Project Id */
            project_id: string;
            /** Locale */
            locale: string;
            /** File */
            file: string | null;
            /** Created */
            created: number;
            /** Filled */
            filled: number;
            /** Updated */
            updated: number;
            /** Unchanged */
            unchanged: number;
            /** Approvals Reset */
            approvals_reset: number;
            /** Removed */
            removed: string[];
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name: string;
            /**
             * Role
             * @default reviewer
             */
            role: string;
            /**
             * Password
             * @description Temporary password
             */
            password: string;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Is Active */
            is_active: boolean;
            /** Assignments */
            assignments: components["schemas"]["AssignmentOut"][];
        };
        /** UserUpdate */
        UserUpdate: {
            /** Name */
            name?: string | null;
            /** Role */
            role?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Password */
            password?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    push_translation_api_projects__projectId__keys__keyPath__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                projectId: string;
                keyPath: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushTranslation"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_translations_api_projects__projectId__keys_export_get: {
        parameters: {
            query: {
                locale: string;
                format?: string;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_status_api_projects__projectId__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_source_api_projects__projectId__source_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceUpload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceUploadResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                stringherd_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                stringherd_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                stringherd_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_admin_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                stringherd_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_admin_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: {
                stringherd_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_assignment_api_admin_users__user_id__assignments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: {
                stringherd_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_assignment_api_admin_users__user_id__assignments__project_id___locale__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
                project_id: string;
                locale: string;
            };
            cookie?: {
                stringherd_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_review_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                stringherd_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewProject"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_strings_api_review_projects__projectId__locales__locale__strings_get: {
        parameters: {
            query?: {
                status?: string | null;
                /** @description Search in key, source and translation */
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                projectId: string;
                locale: string;
            };
            cookie?: {
                stringherd_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewStringPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_approve_api_review_projects__projectId__locales__locale__strings_approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                locale: string;
            };
            cookie?: {
                stringherd_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkApprove"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkApproveResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_string_api_review_projects__projectId__locales__locale__strings__keyPath__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                locale: string;
                keyPath: string;
            };
            cookie?: {
                stringherd_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewString"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
